<?php
namespace ProcessWire;

class WesanoxLottery extends WireData implements Module {
    public static function getModuleInfo()
    {
        return array(
            'title' => 'wesanox Lottery',
            'summary' => 'A lottery Module to connect lotteries from backend with the PW Frontend by wesanox.',
            'version' => '0.1.1',
            'author' => 'Frittenfritze',
            'icon' => 'gift',
            'singular' => true,
            'autoload' => true,
            'requires' => array(
                'ProcessWire>=3.0.210',
                'PHP>=8.0.0',
                'FormBuilder>=0.5.5',
                'WesanoxHelperFields>=0.0.1',
                'WesanoxHelperForms>=0.0.1',
                'WesanoxApi>=0.0.1'
            ),
        );
    }


    protected ?LotteryRequests $requests = null;

    /**
     * @var Module|_Module|null $helper_forms
     * @var Module|_Module|null $helper_fields
     */
    protected Module|_Module|null $helper_forms;
    protected Module|_Module|null $helper_fields;

    /**
     * @var array|string[]
     */
    protected array $forms_array = [];

    /**
     * @var array $fields_array
     */
    protected array $fields_array = [];

    /**
     * @var array|string[]
     */
    protected array $matrix_content_items = [
        'content_lottery_form',
        'content_lottery_register',
        'content_lottery_winning',
    ];

    /**
     * WesanoxLottery constructor.
     *
     * @throws WirePermissionException
     */
    function __construct()
    {
        parent::__construct();

        $this->helper_forms = $this->modules->get('WesanoxHelperForms');
        $this->helper_fields = $this->modules->get('WesanoxHelperFields');

        $this->forms_array = include $this->config->paths->WesanoxLottery . 'config/forms.php';
        $this->fields_array = include $this->config->paths->WesanoxLottery . 'config/fields.php';
    }

    /**
     * @return void
     */
    public function ready(): void
    {
        require_once __DIR__ . '/src/classes/lottery/LotteryRequests.php';
        require_once __DIR__ . '/src/classes/form/FormCustomerCreate.php';
        require_once __DIR__ . '/src/classes/form/FormErrorHandler.php';
        require_once __DIR__ . '/src/classes/form/FormWinnerUpdate.php';
        require_once __DIR__ . '/src/classes/form/FormWinnerRender.php';
        require_once __DIR__ . '/src/classes/form/FormStylesRender.php';
        require_once __DIR__ . '/src/classes/form/FormLinksRender.php';

        $this->formStylesRender = new FormStylesRender();

        $this->formStylesRender->handle();
    }

    /**
     * @return LotteryRequests
     */
    public function lotteryRequests(): LotteryRequests
    {
        return new LotteryRequests();
    }

    /**
     * @return FormCustomerCreate
     */
    public function formCustomerCreate(): FormCustomerCreate
    {
        return new FormCustomerCreate();
    }

    /**
     * @return FormWinnerUpdate
     */
    public function formWinnerUpdate(): FormWinnerUpdate
    {
        return new FormWinnerUpdate();
    }

    /**
     * @return FormWinnerRender
     */
    public function formWinnerRender(): FormWinnerRender
    {
        return new FormWinnerRender();
    }

    /**
     * @return FormLinksRender
     */
    public function formLinksRender(): FormLinksRender
    {
        return new FormLinksRender();
    }

    /**
     * @return FormErrorHandler
     */
    public function formErrorHandler(): FormErrorHandler
    {
        return new FormErrorHandler();
    }

    /**
     * @return void
     * @throws WirePermissionException
     */
    public function ___install(): void
    {
        /**
         * create forms
         */
        $this->helper_forms->createForm($this->forms_array);

        /**
         * create fields
         */
        foreach ($this->fields_array as $field_array) {
            $this->helper_fields->createFields($field_array);
        }

        /**
         * add Matrix item and copy item files
         */
        $this->addMatrixItem($this->fields);

        /**
         * install/copy matrix item files
         */
        foreach ($this->matrix_content_items as $item) {
            $source_dir = $this->config->paths->WesanoxLottery . 'src/fields/{$item}/';
            $target_dir = $this->config->paths->templates . 'fields/matrix_content/{$item}/';

            if(!is_dir($target_dir)) {
                $this->files->mkdir($target_dir, true);
            }

            $this->files->copy($source_dir, $target_dir, [
                'recursive' => true,
                'overwrite' => false
            ]);
        }
    }

    /**
     * @return void
     */
    public function ___uninstall(): void
    {
        /**
         * delete forms
         */
        $this->helper_forms->deleteForm($this->forms_array);
        /**
         * delete fields
         */
        $this->helper_fields->deleteFields($this->fields_array, 'matrix_content', $this->matrix_content_items);

        /**
         * delete matrix item files
         */
        foreach ($this->matrix_content_items as $item) {
            $target_dir = $this->config->paths->templates . 'fields/matrix_content/{$item}/';

            if (is_dir($target_dir)) {
                $this->files->rmdir($target_dir, true);
            }
        }
    }

    /**
     * @param $fields
     *
     * @return void
     * @throws WirePermissionException
     */
    private function addMatrixItem($fields): void
    {
        /**
         * Add new item to matrix_content
         */
        if($fields->get('matrix_content')) {
            $id_lottery_text = $fields->get('text_lottery_form')->id;
            $id_dynamic_api = $fields->get('dynamic_api')->id;
            $id_text_lottery_id = $fields->get('text_lottery_id')->id;
            $id_text_lottery_key = $fields->get('text_lottery_key')->id;
            $id_link_lottery_privacy = $fields->get('link_lottery_privacy')->id;
            $id_link_lottery_terms = $fields->get('link_lottery_terms')->id;

            $f = $fields->get('matrix_content');

            $matrix_template = $f->type->getMatrixTemplate($f);

            $key = $this->helper_fields->getMatrixKey('matrix_content') + 1;

            $f->setArray([
                "matrix{$key}_name"   => 'content_lottery_form',
                "matrix{$key}_label"  => 'Gewinnspielformular',
                "matrix{$key}_head"   => '{matrix_label} [• {matrix_summary}]',
                "matrix{$key}_fields" => [
                    1 => $id_dynamic_api,
                    2 => $id_text_lottery_id,
                    3 => $id_text_lottery_key,
                    4 => $id_lottery_text,
                    5 => $id_link_lottery_privacy,
                    6 => $id_link_lottery_terms
                ],
                "matrix{$key}_sort"   => $key,
            ]);

            $key = $key + 1;

            $f->setArray([
                "matrix{$key}_name"   => 'content_lottery_register',
                "matrix{$key}_label"  => 'Gewinnspielregistierung',
                "matrix{$key}_head"   => '{matrix_label} [• {matrix_summary}]',
                "matrix{$key}_fields" => [
                    1 => $id_dynamic_api,
                ],
                "matrix{$key}_sort"   => $key,
            ]);

            $key = $key + 1;

            $f->setArray([
                "matrix{$key}_name"   => 'content_lottery_winning',
                "matrix{$key}_label"  => 'Gewinnspielabfrage',
                "matrix{$key}_head"   => '{matrix_label} [• {matrix_summary}]',
                "matrix{$key}_fields" => [
                    1 => $id_dynamic_api,
                    2 => $id_lottery_text,
                    3 => $id_link_lottery_privacy,
                    4 => $id_link_lottery_terms
                ],
                "matrix{$key}_sort"   => $key,
            ]);

            $f->save();

            $matrix_template->fieldgroup->add('dynamic_api');
            $matrix_template->fieldgroup->add('text_lottery_form');
            $matrix_template->fieldgroup->add('text_lottery_id');
            $matrix_template->fieldgroup->add('text_lottery_key');
            $matrix_template->fieldgroup->add('link_lottery_privacy');
            $matrix_template->fieldgroup->add('link_lottery_terms');
            $matrix_template->fieldgroup->save();

            $matrix_template->save();
        }
    }
}

