<?php

return [
    [
        'name' => 'text_lottery_id',
        'type' => 'Text',
        'label' => 'Gewinnspiel Backend - ID',
        'tags' => 'lottery',
        'icon' => 'File text o',
        'width' => 25,
        'formatter' => 'TextformatterEntities',
        'inputfieldClass' => null,
    ],
    [
        'name' => 'text_lottery_key',
        'type' => 'Text',
        'label' => 'Gewinnspiel Backend - Key',
        'tags' => 'lottery',
        'icon' => 'File text o',
        'width' => 50,
        'formatter' => 'TextformatterEntities',
        'inputfieldClass' => null,
    ],
    [
        'name' => 'text_lottery_form',
        'type' => 'Textarea',
        'label' => 'Hinweistext nach dem Formular',
        'tags' => 'lottery',
        'icon' => 'File text o',
        'width' => 100,
        'formatter' => '',
        'inputfieldClass' => 'InputfieldCKEditor'
    ],
    [
        'name' => 'link_lottery_privacy',
        'type' => 'Page',
        'label' => 'Link Datenschutz',
        'tags' => 'lottery',
        'icon' => 'Link',
        'width' => 50,
        'derefAsPage' => 2,
        'inputfield' => 'InputfieldPageListSelect',
        'parent_id' => 0,
        'labelFieldName' => 'title',
        'collapsed' => 0,
    ],
    [
        'name' => 'link_lottery_terms',
        'type' => 'Page',
        'label' => 'Link Teilnahmebedingungen',
        'tags' => 'lottery',
        'icon' => 'Link',
        'width' => 50,
        'derefAsPage' => 2,
        'inputfield' => 'InputfieldPageListSelect',
        'parent_id' => 0,
        'labelFieldName' => 'title',
        'collapsed' => 0,
    ],
];