<?php

return [
    [
        'name' => 'lottery-code',
        'settings' => '{
            "required": false,
            "columnWidth": 0,
            "action": "./",
            "method": "post",
            "roles": {
                "form-submit": [
                    "guest"
                ],
                "form-list": [],
                "form-edit": [],
                "form-delete": [],
                "entries-list": [],
                "entries-edit": [],
                "entries-delete": [],
                "entries-page": [],
                "entries-resend": []
            },
            "flags": 0,
            "pluginActions": [],
            "framework": "Basic",
            "allowPreset": 0,
            "skipSessionKey": 0,
            "useCookies": 0,
            "partialEntryDays": 14,
            "spamEntryDays": 7,
            "submitText": "DATEN ABSENDEN",
            "successMessage": "Danke - die Teilnahme wurde erfolgreich registriert.",
            "errorMessage": "Hier ist etwas schief gelaufen - bitte versuche es erneut!",
            "mobilePx": 0,
            "frBasic_noLoad": [],
            "frBasic_cssURL": "/site/modules/FormBuilder/frameworks/basic/main.css",
            "frBasic_itemContent": [
                "description",
                "out",
                "error",
                "notes"
            ],
            "honeypot": [],
            "spamFlags": 0,
            "listFields": [],
            "entryDays": 0,
            "emailSubject": "Form Submission",
            "responderSubject": "Auto-Response",
            "saveFlags": 16,
            "spamWords": [],
            "frBootstrap5_noLoad": [],
            "frBootstrap5_bootURL": "/site/modules/FormBuilder/frameworks/bootstrap5/",
            "spamTimer": 0,
            "children": {
                "code": {
                    "type": "Text",
                    "label": "Promocode oder Gutschein-Code",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 mb-3\ninput:form-control"
                },
                "firstname": {
                    "type": "Text",
                    "label": "Vorname",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 col-lg-6 pe-lg-2 mb-3\ninput:form-control"
                },
                "lastname": {
                    "type": "Text",
                    "label": "Nachname",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 col-lg-6 ps-lg-2 mb-3\ninput:form-control"
                },
                "e_mail": {
                    "type": "Email",
                    "label": "E-Mail",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 250,
                    "showCount": "0",
                    "size": 0,
                    "confirm": 1,
                    "allowIDN": "0",
                    "addClass": "wrap:col-12 mb-3\ninput:form-control"
                },
                "event_id": {
                    "type": "Hidden",
                    "label": "event_id",
                    "required": false,
                    "columnWidth": 0,
                    "addClass": "wrap:d-none"
                },
                "lottery_key": {
                    "type": "Hidden",
                    "label": "key",
                    "required": false,
                    "columnWidth": 0,
                    "addClass": "wrap:d-none"
                },
                "checkbox_action": {
                    "type": "Checkbox",
                    "label": "Ich möchte über weitere Aktionen und Gewinnspiele informiert werden.",
                    "required": false,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "checkedValue": "1",
                    "addClass": "header:visually-hidden"
                },
                "checkbox_privacy": {
                    "type": "Checkbox",
                    "label": "Hiermit akzeptiere ich die Teilnahmebedingungen und Datenschutzhinweise.",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "checkedValue": "1",
                    "addClass": "wrap:mb-3\nheader:visually-hidden"
                },
                "notice": {
                    "type": "Markup",
                    "label": "Notiz",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "useAjax": "0",
                    "allowUserTags": 0,
                    "closeAfterSelect": 1,
                    "delimiter": "s",
                    "maxItems": 0,
                    "textformatters": [],
                    "addClass": "wrap:col-12 mb-3\nheader:visually-hidden"
                }
            }
        }',
    ],
    [
        'name' => 'lottery-normal',
        'settings' => '{
            "required": false,
            "columnWidth": 0,
            "action": "./",
            "method": "post",
            "roles": {
                "form-submit": [
                    "guest"
                ],
                "form-list": [],
                "form-edit": [],
                "form-delete": [],
                "entries-list": [],
                "entries-edit": [],
                "entries-delete": [],
                "entries-page": [],
                "entries-resend": []
            },
            "flags": 0,
            "pluginActions": [],
            "framework": "Basic",
            "allowPreset": 0,
            "skipSessionKey": 0,
            "useCookies": 0,
            "partialEntryDays": 14,
            "spamEntryDays": 7,
            "submitText": "DATEN ABSENDEN",
            "successMessage": "Danke - die Teilnahme wurde erfolgreich registriert.",
            "errorMessage": "Hier ist etwas schief gelaufen - bitte versuche es erneut!",
            "mobilePx": 0,
            "frBasic_noLoad": [],
            "frBasic_cssURL": "/site/modules/FormBuilder/frameworks/basic/main.css",
            "frBasic_itemContent": [
                "description",
                "out",
                "error",
                "notes"
            ],
            "honeypot": [],
            "spamFlags": 0,
            "listFields": [],
            "entryDays": 0,
            "emailSubject": "Form Submission",
            "responderSubject": "Auto-Response",
            "saveFlags": 16,
            "spamWords": [],
            "spamTimer": 0,
            "children": {
                "firstname": {
                    "type": "Text",
                    "label": "Vorname",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 mb-3\ninput: form-control"
                },
                "lastname": {
                    "type": "Text",
                    "label": "Nachname",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 mb-3\ninput: form-control"
                },
                "address": {
                    "type": "Text",
                    "label": "Straße",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 mb-3\ninput:form-control"
                },
                "zip": {
                    "type": "Text",
                    "label": "PLZ",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 col-lg-3 pe-lg-2 mb-3\ninput:form-control"
                },
                "city": {
                    "type": "Text",
                    "label": "Ort",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 col-lg-9 ps-lg-2 mb-3\ninput:form-control"
                },
                "e_mail": {
                    "type": "Email",
                    "label": "E-Mail",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 250,
                    "showCount": "0",
                    "size": 0,
                    "confirm": 1,
                    "allowIDN": "0",
                    "addClass": "wrap:col-12 mb-3\ninput:form-control"
                },
                "phone": {
                    "type": "Text",
                    "label": "Telefon",
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "wrap:col-12 mb-3\ninput:form-control",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0
                },
                "checkbox_privacy": {
                    "type": "Checkbox",
                    "label": "Hiermit akzeptiere ich die Teilnahmebedingungen und Datenschutzhinweise.*",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "warp:col-12 mb-3\nheader:visually-hidden",
                    "checkedValue": "1"
                },
                "notice": {
                    "type": "Markup",
                    "label": "Notiz",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "wrap:col-12 mb-3\nheader:visually-hidden",
                    "textformatters": []
                },
                "event_id": {
                    "type": "Hidden",
                    "label": "event_id",
                    "required": false,
                    "columnWidth": 0,
                    "addClass": "header:d-none"
                },
                "lottery_key": {
                    "type": "Hidden",
                    "label": "key",
                    "required": false,
                    "columnWidth": 0,
                    "addClass": "header:d-none"
                }
            }
        }',
    ],
    [
        'name' => 'lottery-upload',
        'settings' => '{
            "required": false,
            "columnWidth": 0,
            "action": "./",
            "method": "post",
            "roles": {
                "form-submit": [
                    "guest"
                ],
                "form-list": [],
                "form-edit": [],
                "form-delete": [],
                "entries-list": [],
                "entries-edit": [],
                "entries-delete": [],
                "entries-page": [],
                "entries-resend": []
            },
            "flags": 0,
            "pluginActions": [],
            "framework": "Basic",
            "allowPreset": 0,
            "skipSessionKey": 0,
            "useCookies": 0,
            "partialEntryDays": 14,
            "spamEntryDays": 7,
            "submitText": "DATEN ABSENDEN",
            "successMessage": "Danke - die Teilnahme wurde erfolgreich registriert.",
            "errorMessage": "Hier ist etwas schief gelaufen - bitte versuche es erneut!",
            "mobilePx": 0,
            "frBasic_noLoad": [],
            "frBasic_cssURL": "/site/modules/FormBuilder/frameworks/basic/main.css",
            "frBasic_itemContent": [
                "description",
                "out",
                "error",
                "notes"
            ],
            "honeypot": [],
            "spamFlags": 0,
            "listFields": [],
            "entryDays": 0,
            "emailSubject": "Form Submission",
            "responderSubject": "Auto-Response",
            "saveFlags": 16,
            "spamWords": [],
            "spamTimer": 0,
            "children": {
                "receipt": {
                    "type": "FormBuilderFile",
                    "label": "Kassenbon hier hochladen",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "extensions": "gif jpg jpeg png",
                    "maxFileSize": 1048576,
                    "maxFiles": 1,
                    "descRows": 0,
                    "descLength": 2048,
                    "hideInputs": 0,
                    "usePreview": 0,
                    "useHeader": 0,
                    "addClass": "wrap:col-12 mb-3\ninput:form-control",
                    "useMultiple": 0
                },
                "firstname": {
                    "type": "Text",
                    "label": "Vorname",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 mb-3\ninput:form-control"
                },
                "lastname": {
                    "type": "Text",
                    "label": "Nachname",
                    "required": 1,
                    "columnWidth": 100,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-12 mb-3\ninput:form-control"
                },
                "e_mail": {
                    "type": "Email",
                    "label": "E-Mail",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 250,
                    "showCount": "0",
                    "size": 0,
                    "confirm": 1,
                    "allowIDN": "0",
                    "addClass": "wrap:col-12 mb-3\ninput:form-control"
                },
                "checkbox_privacy": {
                    "type": "Checkbox",
                    "label": "Hiermit akzeptiere ich die Teilnahmebedingungen und Datenschutzhinweise.*",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "warp:col-12 mb-3\nheader:visually-hidden",
                    "checkedValue": "1"
                },
                "notice": {
                    "type": "Markup",
                    "label": "Notiz",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "wrap:col-12 mb-3\nheader:visually-hidden",
                    "textformatters": []
                },
                "event_id": {
                    "type": "Hidden",
                    "label": "event_id",
                    "required": false,
                    "columnWidth": 0,
                    "addClass": "header:d-none"
                },
                "lottery_key": {
                    "type": "Hidden",
                    "label": "key",
                    "required": false,
                    "columnWidth": 0,
                    "addClass": "header:d-none"
                }
            }
        }',
    ],
    [
        'name' => 'lottery-winning',
        'settings' => '{
            "required": false,
            "columnWidth": 0,
            "action": "./?winner=signed",
            "method": "post",
            "roles": {
                "form-submit": [
                    "guest"
                ],
                "form-list": [],
                "form-edit": [],
                "form-delete": [],
                "entries-list": [],
                "entries-edit": [],
                "entries-delete": [],
                "entries-page": [],
                "entries-resend": []
            },
            "flags": 0,
            "pluginActions": [],
            "framework": "Basic",
            "allowPreset": 0,
            "skipSessionKey": 0,
            "useCookies": 0,
            "partialEntryDays": 14,
            "spamEntryDays": 7,
            "submitText": "DATEN ABSENDEN",
            "successMessage": "Danke - deine Daten haben wir erhalten!",
            "errorMessage": "Hier ist etwas schief gelaufen - bitte versuche es erneut!",
            "mobilePx": 0,
            "frBasic_noLoad": [],
            "frBasic_cssURL": "/site/modules/FormBuilder/frameworks/basic/main.css",
            "frBasic_itemContent": [
                "description",
                "out",
                "error",
                "notes"
            ],
            "honeypot": [],
            "spamTimer": 0,
            "spamFlags": 0,
            "listFields": [],
            "entryDays": 0,
            "emailSubject": "Form Submission",
            "responderSubject": "Auto-Response",
            "saveFlags": 16,
            "spamWords": [],
            "children": {
                "firstname": {
                    "type": "Text",
                    "label": "Vorname",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-lg-6 pe-lg-2 mb-3\ninput:form-control"
                },
                "lastname": {
                    "type": "Text",
                    "label": "Nachname",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "wrap:col-lg-6 ps-lg-2 mb-3\ninput:form-control",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0
                },
                "mail": {
                    "type": "Text",
                    "label": "E-Mail",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "wrap:col-12 mb-3\ninput:form-control",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0
                },
                "address": {
                    "type": "Text",
                    "label": "Adresse*",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "requiredAttr": 1,
                    "addClass": "wrap:col-12 mb-3\ninput:form-control",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0
                },
                "zip": {
                    "type": "Text",
                    "label": "PLZ*",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "requiredAttr": 1,
                    "addClass": "wrap:col-lg-3 pe-lg-2 mb-3\ninput:form-control"
                },
                "city": {
                    "type": "Text",
                    "label": "Ort / Stadt*",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "requiredAttr": 1,
                    "addClass": "wrap:col-lg-9 ps-lg-2 mb-3\ninput:form-control",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0
                },
                "phone": {
                    "type": "Text",
                    "label": "Telefon",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-lg-6 pe-lg-2 mb-3\ninput:form-control"
                },
                "mobile": {
                    "type": "Text",
                    "label": "Mobile",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "wrap:col-lg-6 ps-lg-2 mb-3\ninput:form-control",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0
                },
                "birthday": {
                    "type": "Datetime",
                    "label": "Geburtstag*",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "inputType": "html",
                    "datepicker": "1",
                    "timeInputSelect": 0,
                    "dateInputFormat": "d.m.Y",
                    "size": 25,
                    "showAnim": "fade",
                    "numberOfMonths": 1,
                    "changeMonth": 1,
                    "changeYear": 1,
                    "showButtonPanel": 0,
                    "showMonthAfterYear": 0,
                    "showOtherMonths": 0,
                    "dateSelectFormat": "yMd",
                    "yearFrom": 1926,
                    "yearTo": 2046,
                    "yearLock": 0,
                    "htmlType": "date",
                    "requiredAttr": 1,
                    "addClass": "wrap:col-lg-6 pe-lg-2 mb-3\ninput:form-control"
                },
                "info": {
                    "type": "Text",
                    "label": "Zusatzinformation",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "minlength": 0,
                    "maxlength": 2048,
                    "showCount": "0",
                    "size": 0,
                    "addClass": "wrap:col-lg-6 ps-lg-2 mb-3\ninput:form-control"
                },
                "checkbox_privacy": {
                    "type": "Checkbox",
                    "label": "Hiermit akzeptiere ich die Datenschutzhinweise.*",
                    "required": 1,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "checkedValue": "1",
                    "addClass": "warp:col-12 mb-3\nheader:sr-only"
                },
                "notice": {
                    "type": "Markup",
                    "label": "Notiz",
                    "required": false,
                    "columnWidth": 0,
                    "collapsed": "0",
                    "addClass": "wrap:col-12 mb-3\nheader:visually-hidden",
                    "textformatters": []
                },
                "winner_id": {
                    "type": "Hidden",
                    "label": "id",
                    "required": false,
                    "columnWidth": 0,
                    "addClass": "wrap:d-none"
                }
            }
        }',
    ]
];